services:
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./migrations:/migrations
    container_name: service
    image: service
    ports:
      - 9000:9000
    depends_on:
      database:
        condition: service_healthy
